-- script to create DB
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
-- TO CREATE TABLE INSIDE IT
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states
(id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(256) NOT NULL);
